project:
  type: website
  output-dir: docs

website:
  title: "Mona Farnisa"
  site-url: https://monafarnisa.github.io/
  
  google-analytics:
    tracking-id: "G-G-W9WW2GESRZ"
    anonymize-ip: true

  navbar: 
    search: true
    left: 
      - text: About
        href: bio.qmd
      - text: Projects
        href: index.qmd
      #- text: Education
      #  href: bio.qmd
      #- text: resume
      #  href: Farnisa_CV_2024.pdf
      - text: Publications
        href: publications.qmd
      - text: biking
        href: biking.qmd
    right: 
      - icon: github
        href: https://github.com/monafarnisa
      - icon: linkedin
        href: https://www.linkedin.com/in/monafarnisa/
  
  page-footer:
    background: light # or dark
    left: Copyright 2024, Mona Farnisa
    right: This website is built with {{< fa brands r-project title="R Project" >}}, [Quarto](https://quarto.org/), and {{< fa brands github >}}


format:
  html:
    css: styles.css
    theme: 
      dark: darkly
      light: literia
    toc: true
    page-layout: full

editor: visual

