project:
  type: website
  output-dir: docs

website:
  title: "Mona Farnisa"
  site-url: https://monafarnisa.github.io/
  favicon: images/favicon-32x32.png

  
  google-analytics:
    tracking-id: "G-G-W9WW2GESRZ"
    anonymize-ip: true

  navbar: 
    search: true
    left: 
      - text: Education & Fieldwork
        href: education.qmd
      - text: Projects
        href: projects.qmd
      - text: Publications
        href: publications.qmd
      - text: Pictures
        href: pictures.qmd
      #text: biking
      #href: biking.qmd
    right: 
      - icon: github
        href: https://github.com/monafarnisa
      - icon: linkedin
        href: https://www.linkedin.com/in/monafarnisa/
      - icon: envelope
        href: farnisamona@gmail.com
  
  page-footer:
    #background: light # or dark
    left: Copyright 2026, Mona Farnisa
    right: This website is built with [Quarto](https://quarto.org/) and {{< fa brands github >}}


format:
  html:
    theme: 
      - darkly
      - styles.scss
    toc: true
    page-layout: full

editor: visual

